version: "3"
services:
  mongo:
    image: "mongo:bionic"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - NODEBB_PL_PASS=plpass
      - NODEBB_EN_PASS=enpass
      - NODEBB_PRIVATE_PASS=privpass
    volumes:
      - "./mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    networks:
      mongo_network:
    command: mongod --bind_ip 127.0.0.1,mongo --auth

  nodebb-pl:
    image: "nodebb/docker"
    ports:
      - "8080:4567"
    depends_on:
      - mongo
  test:
    build:
      context: "./test"
    environment:
      - NODEBB_PL_PASS=plpass
    depends_on:
      - mongo
    command: "tail -f /dev/null"
    networks:
      mongo_network:

networks:
  mongo_network:
    driver: bridge
